name = "workers"
type = "javascript"

zone_id = ""
account_id = "b5cfd1650c6d683007face205f5a81bd"
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"

[vars]
UPSTASH_REDIS_REST_URL = "https://apn1-known-marlin-30903.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AXi3ACQgNzliYzBhMDctZWNlOC00ZjQ4LWIzOGItMzgwOWQ0ZDk0NzNiOThkNTc3MjVmYzk3NDczYWIyN2JiMDA3NWRhMzc3NWU="
PINBOARD_PASSWORD = "bdawg_mcgoo_0613"
PINBOARD_TOKEN = "brandonpittman:E694F748478E78952BD7"
