# (in wrangler.toml)
# Opt into backwards-incompatible changes through September 14, 2021.
compatibility_date = "2023-07-05"
# Also opt into an upcoming fix to the FormData API.
compatibility_flags = [ "streams_enable_constructors" ]

